---
- name: install openjdk and maven
  hosts: build
  become: yes

  tasks:
  - name: Update repositories cache and install "default-jdk" package
    apt:
      name: default-jdk
      update_cache: yes

  - name: Update repositories cache and install "maven" package
    apt:
      name: maven
      update_cache: yes


# - name: install tomcat
#   hosts: web-production
#   become: yes